### ISSUE TITLE
Review viadot tests

### ISSUE THREAD

**Issue by KaterynaIurieva** [dyvenia/viadot#842]
- [x] the issue title describes briefly and clearly the **user story**
- [ ] the project is added
- [ ] the milestone is added, use **backlog** if you don't know the release yet
- [x] you will write a list of **tasks** (like this list) to be closed for this user story

And don't forget to link the closed user stories in your PRs!

## Context

Review viadot tests. Check for duplicates, structure (e. g. no tests for source in tasks), unused commented code.

## Tasks

- [x] Fix issues visible at first sight: unify file naming, remove empty files, clean unused commented code.
- [x] Split files that contains tests for both tasks and sources
- [ ] Check tests coverage 
- [ ] Check for duplicates (automatically using additional library)
- [x] Add missing test (if needed)
