### ISSUE TITLE
Fix issues in tests visible at first sight

### ISSUE THREAD

**Issue by KaterynaIurieva** [dyvenia/viadot#843]
- [ ] the issue title describes briefly and clearly the **user story**
- [ ] the project is added
- [ ] the milestone is added, use **backlog** if you don't know the release yet
- [ ] you will write a list of **tasks** (like this list) to be closed for this user story

And don't forget to link the closed user stories in your PRs!

## Context

This issue is a part of #842 .
Fix issues visible at first sight: unify file naming, remove empty files, clean unused commented code.

## Tasks

- [x]  rename **test__check_if_table_exists**() to **test_check_if_table_exists**()
- [x]  remove comment from **tests/unit/test_base.py**
- [x]  change name of **test___get_col_names_google_analytics_pivoted()**
- [x]  remove comments from **tests/unit/tasks/test_uk_carbon_intensity.py**
- [x]  delete empty file **tests/integration/tasks/test_duckdb.py**
- [x]  rename **tests/integration/tasks/test_genesys_task.py**
- [x]  check commented function in **tests/integration/tasks/test_github.py**
- [x]  change file name **tests/integration/tasks/test_sqlite_insert.py**
- [x]  remove unused tasks in **tests/integration/flows/test_aselite_to_adls.py**

**Comment by trymzet** [comment]
I assume it was done even though no PR is linked
