### ISSUE TITLE
Add a release process

### ISSUE THREAD

**Issue by trymzet** [dyvenia/viadot#948]
## Context

On push of a tag, perform continuous delivery.

## Tasks

- [x] `cd.yml`: release to PyPI
- <s> [ ] `cd.yml`: release docs</s>  -- currently done by internal dyvenia process using ArgoCD
- [x] `cd.yml`: build & push images
- [x] add documentation of the process to `CONTRIBUTING.md`

The release action & process can be adapted from here https://github.com/dyvenia/prefect-viadot/pull/174/files

**Comment by trymzet** [comment]
Done
